version: "3.7"

services:
  db:
    image: postgres:13
    volumes:
      - db:/pgdata
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env.local
volumes:
  db:
    driver: local
  pgdata:
