name: Despliegue a Google Cloud

on:
  push:
    branches:
      - main

env:
  ENVIRONMENT: production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar SSH para acceso a Compute Engine
        run: |
          echo "${{ secrets.ENVIRONMENT.GCE_SSH_PRIVATE_KEY }}" | tr -d '\r' > key
          chmod 600 key
          echo "${{ secrets.ENVIRONMENT.GCE_SSH_PUBLIC_KEY }}" | tr -d '\r' > key.pub
          chmod 600 key.pub

      - name: Añadir clave SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.ENVIRONMENT.GCE_SSH_PRIVATE_KEY }}

      - name: Desplegar a Dokku en Compute Engine
        env:
          GCE_SSH_USER: ${{ secrets.ENVIRONMENT.GCE_SSH_USER }}
          GCE_INSTANCE_IP: ${{ secrets.ENVIRONMENT.GCE_INSTANCE_IP }}
        run: |
          ssh -i key -o StrictHostKeyChecking=no $GCE_SSH_USER@$GCE_INSTANCE_IP << 'EOF'
          cd /home/dokku/app/medusa-admin
          git pull origin main
          git push origin dokku
          EOF

      - name: Finalizar despliegue
        run: echo "El despliegue ha finalizado exitosamente"